### ISSUE TITLE
[Feature] 项目目录外执行异常，需优化

### ISSUE THREAD

**Issue by clgwlg** [ctripcorp/flybirds#1]
**Context**
* 项目名：my_first_project
* 执行目录：/Users/test
* 执行命令：flybirds run --path my_first_project/features/test/android/base_en_click.feature

**错误日志**  

2022-01-11 10:46:26,985 - flybirds_log - INFO - find extend pkg
Exception AttributeError: 'DeviceConfig' object has no attribute 'platform'
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    load_entry_point('behave==1.2.6', 'console_scripts', 'behave')()
  File "/usr/local/lib/python3.7/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)

**优化点**
* 增加执行前环境检查
* 有更明确的异常信息和错误提示
* 支持某些场景下项目目录的自动检测

**Comment by xiaoxiaocaiiao** [comment]
已经添加异常检测
