### ISSUE TITLE
执行flybirds run -P .\features\test\web\web_cn_click.feature报错

### ISSUE THREAD

**Issue by ziyekudeng** [ctripcorp/flybirds#209]
**问题描述 / Describe the bug**
初始化项目后，执行flybirds run -P .\features\test\web\web_cn_click.feature，报错。

**问题复现步骤 / To Reproduce**
2023-11-09 12:24:01,758 - flybirds_log - ERROR - behave task execute error: Traceback (most recent call last):
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\core\launch_cycle\run_manage.py", line 74, in exe
    parallel_run(context)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 58, in parallel_run
    features = get_features_num(cmd)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 144, in get_features_num
    parsed_output = dry_run_parsed_cmd(cmd)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 140, in dry_run_parsed_cmd
    return json.loads(out.decode('utf-8-sig'))
  File "D:\develop_tool\python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\develop_tool\python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\develop_tool\python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**预期结果 / Expected behavior**
执行成功

**截图 / Screenshots**
PS D:\work_research_python\github\CMS_UI_BDD> flybirds run -P .\features\test\web\web_cn_click.feature
2023-11-09 12:24:00,810 - flybirds_log - INFO - flybirds cmd info: .\features\test\web\web_cn_click.feature None --format=json report\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\report.json [] None None True local
2023-11-09 12:24:00,812 - flybirds_log - INFO - report path: -o report\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\report.json
2023-11-09 12:24:00,813 - flybirds_log - INFO - screenshot path: report\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\screenshot
2023-11-09 12:24:00,814 - flybirds_log - INFO - the assembled behave execution command: behave .\features\test\web\web_cn_click.feature --format=json -o report\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\report.json --define screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr
2023-11-09 12:24:00,814 - flybirds_log - INFO - ============last run_args: {'cmd_str': 'behave .\\features\\test\\web\\web_cn_click.feature --format=json -o report\\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\\report.json --define screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': False, 'report_dir_path': 'report\\601ac558-0b02-4e6a-b7b4-0fde8e2553ad', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': '.\\features\\test\\web\\web_cn_click.feature', 'parsed_tags': []}
2023-11-09 12:24:00,814 - flybirds_log - INFO - received run_args: {'cmd_str': 'behave .\\features\\test\\web\\web_cn_click.feature --format=json -o report\\601ac558-0b02-4e6a-b7b4-0fde8e2553ad\\report.json --define screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': False, 'report_dir_path': 'report\\601ac558-0b02-4e6a-b7b4-0fde8e2553ad', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': '.\\features\\test\\web\\web_cn_click.feature', 'parsed_tags': []}
2023-11-09 12:24:00,825 - flybirds_log - INFO - find extend pkg
2023-11-09 12:24:00,882 - flybirds_log - INFO - use_define: ['--define', 'screenShotDir=cmVwb3J0XDYwMWFjNTU4LTBiMDItNGU2YS1iN2I0LTBmZGU4ZTI1NTNhZFxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw=']
2023-11-09 12:24:01,669 - flybirds_log - INFO - change behave json format feature to flybirds feature
2023-11-09 12:24:01,670 - flybirds_log - INFO - change behave add_step_definition to flybirds add_step_definition
2023-11-09 12:24:01,758 - flybirds_log - ERROR - behave task execute error: Traceback (most recent call last):
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\core\launch_cycle\run_manage.py", line 74, in exe
    parallel_run(context)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 58, in parallel_run
    features = get_features_num(cmd)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 144, in get_features_num
    parsed_output = dry_run_parsed_cmd(cmd)
  File "D:\develop_tool\python\Python39\lib\site-packages\flybirds\report\parallel_runner.py", line 140, in dry_run_parsed_cmd
    return json.loads(out.decode('utf-8-sig'))
  File "D:\develop_tool\python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\develop_tool\python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\develop_tool\python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
2023-11-09 12:39:33,586 - flybirds_log - INFO - flybirds cmd info: .\features\test\web\web_cn_click.feature None --format=json report\bb062c77-390d-4c61-84ce-c1b29d763565\report.json [] None None True local
2023-11-09 12:39:33,587 - flybirds_log - INFO - report path: -o report\bb062c77-390d-4c61-84ce-c1b29d763565\report.json
2023-11-09 12:39:33,588 - flybirds_log - INFO - screenshot path: report\bb062c77-390d-4c61-84ce-c1b29d763565\screenshot
2023-11-09 12:39:33,589 - flybirds_log - INFO - the assembled behave execution command: behave .\features\test\web\web_cn_click.feature --format=json -o report\bb062c77-390d-4c61-84ce-c1b29d763565\report.json --define screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr
2023-11-09 12:39:33,589 - flybirds_log - INFO - ============last run_args: {'cmd_str': 'behave .\\features\\test\\web\\web_cn_click.feature --format=json -o report\\bb062c77-390d-4c61-84ce-c1b29d763565\\report.json --define screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': False, 'report_dir_path': 'report\\bb062c77-390d-4c61-84ce-c1b29d763565', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': '.\\features\\test\\web\\web_cn_click.feature', 'parsed_tags': []}
2023-11-09 12:39:33,589 - flybirds_log - INFO - received run_args: {'cmd_str': 'behave .\\features\\test\\web\\web_cn_click.feature --format=json -o report\\bb062c77-390d-4c61-84ce-c1b29d763565\\report.json --define screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': False, 'report_dir_path': 'report\\bb062c77-390d-4c61-84ce-c1b29d763565', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': '.\\features\\test\\web\\web_cn_click.feature', 'parsed_tags': []}
2023-11-09 12:39:33,597 - flybirds_log - INFO - find extend pkg
2023-11-09 12:39:33,650 - flybirds_log - INFO - use_define: ['--define', 'screenShotDir=cmVwb3J0XGJiMDYyYzc3LTM5MGQtNGM2MS04NGNlLWMxYjI5ZDc2MzU2NVxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw=']
2023-11-09 12:39:34,678 - flybirds_log - INFO - change behave json format feature to flybirds feature
2023-11-09 12:39:34,678 - flybirds_log - INFO - change behave add_step_definition to flybirds add_step_definition
2023-11-09 12:39:34,774 - flybirds_log - ERROR - behave task execute error: Traceback (most recent call last):
  File "d:\develop_tool\python\python38\lib\site-packages\flybirds\core\launch_cycle\run_manage.py", line 74, in exe
    parallel_run(context)
  File "d:\develop_tool\python\python38\lib\site-packages\flybirds\report\parallel_runner.py", line 58, in parallel_run
    features = get_features_num(cmd)
  File "d:\develop_tool\python\python38\lib\site-packages\flybirds\report\parallel_runner.py", line 144, in get_features_num
    parsed_output = dry_run_parsed_cmd(cmd)
  File "d:\develop_tool\python\python38\lib\site-packages\flybirds\report\parallel_runner.py", line 140, in dry_run_parsed_cmd
    return json.loads(out.decode('utf-8-sig'))
  File "d:\develop_tool\python\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "d:\develop_tool\python\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\develop_tool\python\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-11-09 12:39:34,776 - flybirds_log - INFO - start generate report
2023-11-09 12:39:34,776 - flybirds_log - INFO - report cmd:node "d:\develop_tool\python\python38\lib\site-packages\flybirds\report\node_report\report.js" report\bb062c77-390d-4c61-84ce-c1b29d763565 report\bb062c77-390d-4c61-84ce-c1b29d763565 web
Active code page: 65001
multiple-cucumber-html-reporter platform: web
WARNING: No JSON files found in 'report\bb062c77-390d-4c61-84ce-c1b29d763565'. NO REPORT CAN BE CREATED!
lodash.templateSources[1]:10
 _.each(suite.features[0].metadata, function(metadatum, metadatumIndex) { ;
                          ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at eval (lodash.templateSources[1]:10:27)
    at _createFeaturesOverviewIndexPage (d:\develop_tool\python\python38\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:455:84)
    at Object.generateReport [as generate] (d:\develop_tool\python\python38\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:139:3)
    at Object.<anonymous> (d:\develop_tool\python\python38\lib\site-packages\flybirds\report\node_report\report.js:46:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1
PS D:\work_research_python\github\CMS_UI_BDD> 

**环境信息 / Environment (please complete the following information):**
 - win11
 - python 3.8.10
 - node 18.17.1
 - Version [0.6.17]

**Additional context**

**Comment by ylscsdb** [comment]
[https://github.com/ctripcorp/flybirds/issues/207](url)
