### ISSUE TITLE
操作步骤: 点击[], 超时时间没有生效

### ISSUE THREAD

**Issue by jasmineamber** [ctripcorp/flybirds#30]
**问题描述 / Describe the bug**
点击[#delay_btn, timeout=10]
flybirds_config.json中的“waitEleTimeout”和步骤中指定的timeout都没有生效

**问题复现步骤 / To Reproduce**
1. 测试网页
```
<html>
    <body>
        Test Timeout
    </body>
    <script>
        setTimeout(function(){
            var button = document.createElement("button");
            button.setAttribute("id", "delay_btn");
            button.innerHTML = "Submit";
            document.body.appendChild(button);
        }, 1000);
    </script>
</html>
```
2. test.feature
```
# language: zh-CN
功能: web点击

  场景: 点击元素
    假如 跳转页面到[http://127.0.0.1:5500/show.html]
      而且 点击[#delay_btn, timeout=10]
    那么 全屏截图
```
3. 执行报错
```
2022-05-19 12:48:20,999 - flybirds_log - INFO - [scenario_OnAfter] start!
2022-05-19 12:48:21,000 - flybirds_log - INFO - [scenario_fail] feature:web点击, scenario:点击元素 failed to run
2022-05-19 12:48:21,001 - flybirds_log - INFO - [scenario_fail] step:点击[#delay_btn, timeout=10]
2022-05-19 12:48:21,001 - flybirds_log - ERROR - [scenario_fail] step error msg:Traceback (most recent call last):
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/utils/dsl_helper.py", line 171, in wrapper_func
    func(*args, **kwargs)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/core/dsl/step/element.py", line 49, in click_ele
    g_Context.step.click_ele(context, selector)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/core/plugin/plugins/default/web/step.py", line 71, in click_ele
    ele.ele_click(context, selector)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/core/plugin/plugins/default/web/element.py", line 103, in ele_click
    locator = self.get_ele_locator(param)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/core/plugin/plugins/default/web/element.py", line 68, in get_ele_locator
    selector_node, selector_str = self.get_ele_handle(selector)
  File "/home/john/VSProjects/LearnFlybirds/venv/lib/python3.7/site-packages/flybirds/core/plugin/plugins/default/web/element.py", line 89, in get_ele_handle
    raise FlybirdsVerifyEleException(selector=selector_str)
flybirds.core.exceptions.FlybirdsVerifyEleException: Timeout 35000ms exceeded.
==================== logs ====================
waiting for selector "text=#delay_btn"
==============================================
```

**预期结果 / Expected behavior**
timeout 查找“字符串”的超时时间，优先级：默认值 < flybirds_config.json中的“waitEleTimeout” < 语句中指定

**环境信息 / Environment (please complete the following information):**
 - Browser [e.g. chromium]
 - Version [e.g. 0.2.2]

**Comment by DHpie** [comment]
web端的 timeout 由 `flybirds_config.json里的 frame_info.waitEleTimeout`  配置决定。
方便的话，可以贴一下你的`flybirds_config.json` 配置

**Comment by jasmineamber** [comment]
配置是用 `flybirds create` 创建生成的, 就改了失败重试次数.
```
{
  "app_info": {
    "packageName": "ctrip.android.view",
    "packagePath": "https://download2.ctrip.com/html5/Ctrip_V8.43.0_SIT4-100053_Product_9725895.apk",
    "overwriteInstallation": false,
    "uniqueTag": "",
    "defaultUser": null,
    "defaultPassword": null
  },
  "device_info": {
    "deviceId": "127.0.0.1:8200",
    "platform": "web",
    "webDriverAgent": "com.fd.test.WebDriverAgentLib.xctrunner"
  },
  "web_info": {
    "headless": true,
    "browserType": [
      "chromium"
    ],
    "defaultTimeout": 30
  },
  "flow_behave": {
    "beforeRunPage": "restartApp",
    "scenarioFailPage": "restartApp",
    "scenarioSuccessPage": "None",
    "beforeRunLogin": false,
    "failScreenRecord": true,
    "scenarioScreenRecordTime": 120,
    "failRerun": false,
    "maxFailRerunCount": 1.0,
    "maxRetryCount": 0
  },
  "frame_info": {
    "waitEleTimeout": 35,
    "waitEleDisappear": 10,
    "clickVerifyTimeout": 15,
    "useSwipeDuration": false,
    "swipeDuration": 6,
    "usePocoInput": true,
    "afterInputWait": 1,
    "useSearchSwipeDuration": false,
    "searchSwipeDuration": 1,
    "swipeSearchCount": 5,
    "swipeSearchDistance": 0.3,
    "pageRenderTimeout": 65,
    "appStartTime": 6,
    "swipeReadyTime": 3,
    "verifyPosNotChangeCount": 5,
    "screenRecordTime": 90,
    "useSnap": true
  },
  "report": {},
  "log": {}
}
```

**Comment by DHpie** [comment]
看起来并没有什么问题。 web端 暂不支持可选参数，可以尝试把这个step里面的 ` timeout=10` 去掉。 如下：
> 而且 点击[#delay_btn]

**Comment by jasmineamber** [comment]
1. 去掉也是一样的结果
2. 直接使用playwright也是一样的结果
```
from playwright.sync_api import Playwright, sync_playwright, expect, Page

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()

    page = context.new_page()
    page.set_default_timeout(30000)

    page.goto("http://127.0.0.1:5500/show.html")

    # page.wait_for_timeout(3000) # 查找前等待, 则query_selector不会报错
    page.query_selector("#delay_btn").click() # 报错 'NoneType' object has no attribute 'click'
    # page.locator("#delay_btn").click() # 正常点击

    page.close()
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

```

**Comment by DHpie** [comment]
>    page.wait_for_timeout(3000) # 查找前等待, 则query_selector不会报错
    page.query_selector("#delay_btn").click() # 报错 'NoneType' object has no attribute 'click'

这个位置，你等待3秒后，page能正常点击吗？ 

我目前没能重现这个问题，一般`page.locator`  能操作的元素，在我这边`query_selector` 都能定位到。 不过可以肯定的是 `page.set_default_timeout(30000)`  确实对 `query_selector`  不生效。

如果上述问题存在，那确实是个bug.

**Comment by jasmineamber** [comment]
等待3秒后, query_selector能正常点击

**Comment by DHpie** [comment]
非常感谢你的反馈， 后续版本会进行修复。
