### ISSUE TITLE
flybirds run -P features/test/android MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by shopconan** [ctripcorp/flybirds#33]
**问题描述 / Describe the bug**

**问题复现步骤 / To Reproduce**
**预期结果 / Expected behavior**

**截图 / Screenshots**

**环境信息 / Environment (please complete the following information):**

**Additional context**

请问adb devices这里能使用bluestack模拟器吗

我按照教程操作下来
```
(base) PS D:\Download\audio-visual\saas\data\indiehackerebooks> flybirds create
Welcome to flybirds cli. Please enter any information to continue.
Please input your project name>>: indie
Please input your test platform? (Android/IOS/Web): android
Do you want to configure your deviceId now?(this step can be skipped) [y/N]: y
Please input your deviceId?: emulator-5554
Do you want to configure your packageName now?(this step can be skipped) [y/N]: n
You can configure your packageName later in the project's flybirds_config.json file.
Cloning into 'indie'...
Processing  [####################################]  100%
Done it! Create Project indie has success!
You can find it at: D:\Download\audio-visual\saas\data\indiehackerebooks\indie
(base) PS D:\Download\audio-visual\saas\data\indiehackerebooks> flybirds run -P features/test/android
2022-05-21 06:39:46,394 - flybirds_log - INFO - flybirds cmd info: features/test/android None --format=json report\b6a71e7f-e8a6-443e-8db8-764e94d29c0c\report.json () True None True local
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\anaconda3\Scripts\flybirds.exe\__main__.py", line 7, in <module>
  File "D:\Program Files\anaconda3\lib\site-packages\flybirds\launcher.py", line 13, in main
    cli_main.app()
  File "D:\Program Files\anaconda3\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Program Files\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Program Files\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Program Files\anaconda3\lib\site-packages\flybirds\cli\__main__.py", line 76, in runner
    run_args = parse_args(
  File "D:\Program Files\anaconda3\lib\site-packages\flybirds\cli\parse_args.py", line 47, in parse_args
    check_workspace_args(feature_path)
  File "D:\Program Files\anaconda3\lib\site-packages\flybirds\cli\parse_args.py", line 31, in check_workspace_args
    raise Exception(f"not find config directory in {base_dir}")
Exception: not find config directory in D:\Download\audio-visual\saas\data\indiehackerebooks
(base) PS D:\Download\audio-visual\saas\data\indiehackerebooks> cd .\indie\
(base) PS D:\Download\audio-visual\saas\data\indiehackerebooks\indie> flybirds run -P features/test/android
2022-05-21 06:40:21,391 - flybirds_log - INFO - flybirds cmd info: features/test/android None --format=json report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\report.json () True None True local
2022-05-21 06:40:21,391 - flybirds_log - INFO - report path: -o report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\report.json
2022-05-21 06:40:21,392 - flybirds_log - INFO - screenshot path: report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\screenshot
2022-05-21 06:40:21,392 - flybirds_log - INFO - the assembled behave execution command: behave features/test/android --format=json -o report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\report.json --define screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr
2022-05-21 06:40:21,392 - flybirds_log - INFO - ============last run_args: {'cmd_str': 'behave features/test/android --format=json -o report\\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\\report.json --define screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': True, 'report_dir_path': 'report\\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': 'features/test/android', 'parsed_tags': []}
2022-05-21 06:40:21,392 - flybirds_log - INFO - received run_args: {'cmd_str': 'behave features/test/android --format=json -o report\\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\\report.json --define screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90 --define run_at=bG9jYWw= --no-color --no-capture --no-capture-stderr', 'need_rerun': True, 'report_dir_path': 'report\\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2', 'use_define': ['--define', 'screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw='], 'env_config': None, 'report_format': '--format=json', 'html': True, 'run_at': 'local', 'processes': 4, 'feature_path': 'features/test/android', 'parsed_tags': []}
2022-05-21 06:40:21,399 - flybirds_log - INFO - find extend pkg
2022-05-21 06:40:21,766 - flybirds_log - INFO - use_define: ['--define', 'screenShotDir=cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90', '--define', 'run_at=bG9jYWw=']
2022-05-21 06:40:24,090 - flybirds_log - INFO - change behave json format feature to flybirds feature
2022-05-21 06:40:24,091 - flybirds_log - INFO - change behave add_step_definition to flybirds add_step_definition
2022-05-21 06:40:24,127 - flybirds_log - INFO - [before_all_hook] user_data:{'screenShotDir': 'cmVwb3J0XDI3OTBlYjgwLWQ0MDEtNGFjNy1iYmQxLThjMGU2YTA3NjVlMlxzY3JlZW5zaG90', 'run_at': 'bG9jYWw='}
2022-05-21 06:40:24,127 - flybirds_log - INFO - [loader] user_data: {'screenShotDir': 'report\\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2\\screenshot', 'run_at': 'local'}
2022-05-21 06:40:24,129 - flybirds_log - INFO - [loader] run platform: android
D:\Program Files\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\Program Files\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
D:\Program Files\anaconda3\lib\site-packages\numpy\.libs\libopenblas.xwydx2ikjw2nmtwsfyngfuwkqu3lytcz.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
HOOK-ERROR in before_all: ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (D:\Program Files\anaconda3\lib\site-packages\cv2\cv2.cp38-win_amd64.pyd)
HOOK-ERROR in after_all: AttributeError: 'NoneType' object has no attribute 'device_info'

ABORTED: By user.
0 features passed, 0 failed, 0 skipped, 11 untested
0 scenarios passed, 0 failed, 0 skipped, 23 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 117 untested
Took 0m0.000s
2022-05-21 06:40:24,390 - flybirds_log - INFO - Feature sum_count rerun after creation failure <= 0 or fail_count <= 0
2022-05-21 06:40:24,390 - flybirds_log - INFO - True
2022-05-21 06:40:24,396 - flybirds_log - INFO - Do you need to rerun the task: False, the failed retry task was not executed
2022-05-21 06:40:24,396 - flybirds_log - INFO - Start processing the json report. report_dir_path: [report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2],rerun_report_dir_path:[None]
2022-05-21 06:40:24,398 - flybirds_log - INFO - start generate report
2022-05-21 06:40:24,398 - flybirds_log - INFO - report cmd:node D:\Program Files\anaconda3\lib\site-packages\flybirds\report\node_report\report.js report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2 report\2790eb80-d401-4ac7-bbd1-8c0e6a0765e2 android
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
```

(base) PS D:\Download\audio-visual\saas\data\indiehackerebooks\indie> adb devices
List of devices attached
emulator-5554   offline

**Comment by clgwlg** [comment]
我们测试过Google的Android virtual Device，可以正常工作。
从你提供的信息看，emulator-5554是offline状态，建议你先使用adb命令，检查是否可以正常连接
```
adb connect device_ip_address:5555    // device_ip_address:5555 为模拟器的设备号和端口号
```
接下来确认主机已连接到目标设备
```
$ adb devices
List of devices attached
device_ip_address:5555 device
```
最后，你可以将测试通过的设备信息，配置到flybirds_config.json
deviceId = xxx , 例如："10.5.170.85:5555"

**Comment by shopconan** [comment]
ok 我应该是没有连接上去
