### ISSUE TITLE
运行 web的demo用例，报错

### ISSUE THREAD

**Issue by chase001** [ctripcorp/flybirds#47]
**问题描述 / Describe the bug**

**问题复现步骤 / To Reproduce**
1.(venv) PS E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test> flybirds run -D platform=web -P features/test/web

2022-06-09 14:58:46,534 - flybirds_log - INFO - report cmd:node E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\report.js report\18767f45-9780-4f4d-98bc-decdfca54c95 report\18767f45-9
780-4f4d-98bc-decdfca54c95 web
multiple-cucumber-html-reporter platform: web
lodash.templateSources[1]:10
 _.each(suite.features[0].metadata, function(metadatum, metadatumIndex) { ;
                          ^

TypeError: Cannot read property 'metadata' of undefined
    at eval (lodash.templateSources[1]:10:27)
    at _createFeaturesOverviewIndexPage (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:455:84)
    at Object.generateReport [as generate] (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:139:3)
    at Object.<anonymous> (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\report.js:46:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**预期结果 / Expected behavior**

**截图 / Screenshots**

**环境信息 / Environment (please complete the following information):**
 - OS: [WIN 10]

**Additional context**

**Comment by clgwlg** [comment]
请提供下当前使用的flybirds的版本，之前有用户反馈过这个问题，在某些环境下会出现，因此在最近的v0.2.4版本，增加了处理逻辑。查看版本方法：
```
pip show flybirds
```

**Comment by chase001** [comment]
Name: flybirds
Version: 0.2.4
Summary: BDD-driven natural language automated testing framework
Home-page: https://github.com/ctripcorp/flybirds
Author: trip_flight
Author-email: flybirds_support@trip.com
License: MIT license
Location: e:\chase_code\autotest_pc\gsol_-pc_-auto-test\venv\lib\site-packages
Requires: airtest, behave, click, deepdiff, jsonpath, jsonpath-ng, playwright, pocoui, pyasn1, pyOpenSSL, setuptools, tidevice, typer
Required-by: 
(venv) PS E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test>

**Comment by clgwlg** [comment]
请看下运行报错信息是否包含下面的内容( Unexpected UTF-8 BOM)，谢谢
```
2022-05-23 13:35:38,205 - flybirds_log - INFO - change behave add_step_definition to flybirds add_step_definition
2022-05-23 13:35:38,315 - flybirds_log - ERROR - behave task execute error: Traceback (most recent call last):
  File "D:\Programs\anaconda\lib\site-packages\flybirds\core\launch_cycle\run_manage.py", line 74, in exe
    parallel_run(context)
  File "D:\Programs\anaconda\lib\site-packages\flybirds\report\parallel_runner.py", line 58, in parallel_run
    features = get_features_num(cmd)
  File "D:\Programs\anaconda\lib\site-packages\flybirds\report\parallel_runner.py", line 136, in get_features_num
    parsed_output = dry_run_parsed_cmd(cmd)
  File "D:\Programs\anaconda\lib\site-packages\flybirds\report\parallel_runner.py", line 132, in dry_run_parsed_cmd
    return json.loads(out.decode())
  File "D:\Programs\anaconda\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

**Comment by chase001** [comment]
所有报错日志：

2022-06-14 13:41:36,774 - flybirds_log - ERROR - Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Users\user\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-tim
er-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensi
ons --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidU
nnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-prof
ile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,a
vailableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\user\AppData\Local\Temp\playwright_chromiumdev_profile-hRPJzP --remote-debugging-pipe --no-startup-window
<launched> pid=3864
[pid=3864][out] Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 9515
[pid=3864][out] Only local connections are allowed.
[pid=3864][out] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[pid=3864][out] ChromeDriver was started successfully.
============================================================
2022-06-14 13:41:36,775 - flybirds_log - INFO - global initialization error
2022-06-14 13:41:36,776 - flybirds_log - INFO - Traceback (most recent call last):
  File "E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\core\plugin/event\web_run.py", line 62, in run
    OnBefore.init_ui_driver(context)
  File "E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\core\plugin/event\web_run.py", line 32, in init_ui_driver
    play_wright, browser = ui_driver.init_driver()
TypeError: cannot unpack non-iterable NoneType object

2022-06-14 13:41:36,785 - flybirds_log - INFO - [web run] OnAfter run event!
E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\behave\runner.py:575: RuntimeWarning: coroutine 'PipeTransport.wait_until_stopped' was never awaited
  if statement:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-06-14 13:41:36,862 - flybirds_log - INFO - parallel run result: ['Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'F
ailed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Fai
led', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed', 'Failed']
2022-06-14 13:41:36,863 - flybirds_log - INFO - all thread done...
2022-06-14 13:41:36,932 - flybirds_log - INFO - Feature sum_count rerun after creation failure <= 0 or fail_count <= 0
2022-06-14 13:41:36,932 - flybirds_log - INFO - True
2022-06-14 13:41:36,938 - flybirds_log - INFO - Do you need to rerun the task: False, the failed retry task was not executed
2022-06-14 13:41:36,939 - flybirds_log - INFO - Start processing the json report. report_dir_path: [report\8bcae1ab-c30b-4e3b-8941-e36434649416],rerun_report_dir_path:[None]
2022-06-14 13:41:37,005 - flybirds_log - INFO - start generate report
2022-06-14 13:41:37,006 - flybirds_log - INFO - report cmd:node E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\report.js report\8bcae1ab-c30b-4e3b-8941-e36434649416 report\8bcae1ab-c
30b-4e3b-8941-e36434649416 web
multiple-cucumber-html-reporter platform: web
lodash.templateSources[1]:10
 _.each(suite.features[0].metadata, function(metadatum, metadatumIndex) { ;
                          ^

TypeError: Cannot read property 'metadata' of undefined
    at eval (lodash.templateSources[1]:10:27)
    at _createFeaturesOverviewIndexPage (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:455:84)
    at Object.generateReport [as generate] (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:139:3)
    at Object.<anonymous> (E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test\venv\lib\site-packages\flybirds\report\node_report\report.js:46:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(venv) PS E:\chase_code\AutoTest_PC\gsol_-pc_-auto-test>

**Comment by clgwlg** [comment]
从日志看，PlayWright使用的chromium浏览器环境，可能遇到了问题
1. 你尝试下修改为其它浏览器类型为试试呢？比如：Firefox
注意检查PlayWright是否已安装好对应的浏览器，Windows通常在以下目录 `%USERPROFILE%\AppData\Local\ms-playwright`

2. 或者尝试重新安装浏览器
```
playwright install  --force
```

**Comment by chase001** [comment]
是用本地的chrome,但是chrome本地项目是能调起Chrome运行的，假如要用我本地的chrome要在那配置啊

**Comment by chase001** [comment]
还有公司网络都配置了代理，导致下载不了，怎么配置：laywright install的下载代理呢？

**Comment by clgwlg** [comment]
默认情况下，Playwright 从 Microsoft CDN 下载浏览器
1. 你可以将 Playwright 配置为使用PLAYWRIGHT_DOWNLOAD_HOSTenv 变量从自定义位置下载。
参考文档：https://playwright.dev/docs/browsers#download-from-artifact-repository

2. 或者你可以手动下载浏览器文件，复制到公司电脑目录下
- %USERPROFILE%\AppData\Local\ms-playwright on Windows
- ~/Library/Caches/ms-playwright on MacOS
- /.cache/ms-playwright on Linux
